# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Your description...', max_length=2048),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rendered_description',
            field=models.CharField(default='<p>Your description...</p>', max_length=4096),
        ),
    ]
