# Generated by Django 5.2.2 on 2025-06-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP MATERIALIZED VIEW IF EXISTS mainapp_latestmodel;
                DROP VIEW IF EXISTS mainapp_latestmodel_categories;
            """
        ),
        migrations.DeleteModel(
            name='LatestModel',
        ),
        migrations.DeleteModel(
            name='ModelCategories',
        ),
    ]
