# Generated by Django 5.2.2 on 2025-07-07 17:35

from django.db import migrations, models

def populate_latest_field(apps, schema_editor):
    """
    Identifies the latest revision for each model_id and sets its 'latest' field to True.
    """

    db_alias = schema_editor.connection.alias
    Model = apps.get_model("mainapp", "Model")
    unique_model_ids = Model.objects.using(db_alias).values_list('model_id', flat=True).distinct()

    for model_id in unique_model_ids:
        latest_revision_obj = Model.objects.using(db_alias).filter(
            model_id=model_id
        ).order_by('-revision').first()

        if latest_revision_obj:
            latest_revision_obj.latest = True
            latest_revision_obj.save(update_fields=['latest'])

def reverse_populate_latest_field(apps, schema_editor):
    """
    sets all 'latest' fields back to False.
    """

    db_alias = schema_editor.connection.alias
    Model = apps.get_model("mainapp", "Model")
    Model.objects.using(db_alias).update(latest=False)

class Migration(migrations.Migration):

    dependencies = [
        
        ('mainapp', '0002_delete_latestmodel_delete_modelcategories_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_latest_field, reverse_populate_latest_field),
    ]
