# Generated by Django 5.2.2 on 2025-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0001_initial'),
        ('mainapp', '0003_populate_latest_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
