# Generated by Django 5.2.2 on 2025-07-06 06:19

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_ban_id_alter_category_id_alter_change_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('revision', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('rendered_description', models.CharField(max_length=1024)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('license', models.IntegerField()),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('rotation', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('translation_x', models.FloatField(default=0.0)),
                ('translation_y', models.FloatField(default=0.0)),
                ('translation_z', models.FloatField(default=0.0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='mainapp.category')),
                ('location', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.location')),
            ],
        ),
    ]
