# Generated by Django 5.2.2 on 2025-06-10 19:17

from django.core.management import call_command
from django.db import migrations


def recreate_pgviews(apps, schema_editor):
    call_command('sync_pgviews', '--force')
    from mainapp.models import LatestModel
    LatestModel.refresh(concurrently=True)


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_ban_id_alter_category_id_alter_change_id_and_more'),
    ]

    operations = [
        migrations.RunPython(recreate_pgviews, reverse_code=migrations.RunPython.noop),
    ]
