# Generated by Django 5.2.2 on 2025-08-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_model_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
