# Generated by Django 5.2.2 on 2025-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_latestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestmodel',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
