# Generated by Django 5.2.2 on 2025-08-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='rotation',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='scale',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_z',
            field=models.FloatField(default=None, null=True),
        ),
    ]
