# Generated by Django 5.2.2 on 2025-08-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='model',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='model',
            name='translation_x',
        ),
        migrations.RemoveField(
            model_name='model',
            name='translation_y',
        ),
        migrations.RemoveField(
            model_name='model',
            name='translation_z',
        ),
    ]
