# Generated by Django 5.2.2 on 2025-09-02 11:51

from django.db import migrations


def update_openstreetmap_provider(apps, schema_editor):
    UserSocialAuth = apps.get_model('social_django', 'UserSocialAuth')
    UserSocialAuth.objects.filter(provider='openstreetmap').update(provider='openstreetmap-oauth2')

def reverse_openstreetmap_provider(apps, schema_editor):
    UserSocialAuth = apps.get_model('social_django', 'UserSocialAuth')
    UserSocialAuth.objects.filter(provider='openstreetmap-oauth2').update(provider='openstreetmap')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_model_rotation_alter_model_scale_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_openstreetmap_provider,
            reverse_openstreetmap_provider,
        ),
    ]