# Generated by Django 6.0 on 2026-01-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_update_osm_oauth2_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='rotation',
            field=models.FloatField(default=0.0, help_text='Rotation in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='scale',
            field=models.FloatField(default=1.0, help_text='Scale factor', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_x',
            field=models.FloatField(default=0.0, help_text='X translation', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_y',
            field=models.FloatField(default=0.0, help_text=' Y translation', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='translation_z',
            field=models.FloatField(default=0.0, help_text='Z translation', null=True),
        ),
    ]
